export const UI_COPY = {
  title: "Workspace Coding Agent Demo",
  eyebrow: "Cloudflare Workspace × GitHub × Agents",
  subtitle: "Import a public GitHub repository, inspect its Workspace files, and then continue in a durable working copy through chat.",
  importLabel: "GitHub repository",
  importPlaceholder: "owner/repo",
  refPlaceholder: "optional ref",
  importAction: "Import repo",
  filesTitle: "Workspace files",
  activeWorkingCopyLabel: "Active working copy",
  applyWorkingCopyAction: "Apply working copy",
  discardWorkingCopyAction: "Discard working copy",
  chatTitle: "Coding agent",
  chatPlaceholder: "Ask the agent to inspect or edit this repo…",
} as const;
