import type { RunEventInput } from "../runs";

export function hasSuccessfulValidation(events: readonly RunEventInput[]): boolean {
  return events.some((event) => {
    if (event.kind !== "agent_tool_result" && event.kind !== "tool_result") return false;
    const detail = parseDetail(event.detail);
    return detail.command === "npm run check" && detail.exitCode === 0;
  });
}

export function completionSummaryAfterValidatedTurnFailure(error: unknown): string {
  const message = error instanceof Error ? error.message : String(error);
  return [
    "The runtime completed the task work and npm run check passed.",
    "Kimi's final response failed after validation, so this summary was generated by the run harness.",
    `Final response error: ${message}`,
  ].join("\n\n");
}

function parseDetail(detail: string): { command?: unknown; exitCode?: unknown } {
  try {
    const parsed = JSON.parse(detail) as unknown;
    return parsed && typeof parsed === "object" && !Array.isArray(parsed)
      ? (parsed as { command?: unknown; exitCode?: unknown })
      : {};
  } catch {
    return {};
  }
}
